### ISSUE TITLE
Got error when trying to run .ts-file

### ISSUE THREAD

**Issue by skalashnyk** [bluelovers/idea-run-typescript#1]
Got error when trying to run .ts-file
IDE: WebStorm 2018.2.1 EAP
> Error running 'test-2.ts': io.plugin.tsnode.execution.TsRunConfiguration cannot be cast to org.jetbrains.debugger.DebuggableRunConfiguration

**Comment by bluelovers** [comment]
@skalashnyk current only support run

not support debug mode
(because i don't know what api for it

and u should only see `run` button

**Comment by skalashnyk** [comment]
@bluelovers , I got this message when pushed "run" button
<img width="275" alt="screen shot 2018-08-06 at 4 52 23 pm" src="https://user-images.githubusercontent.com/18640514/43720631-53e2b916-9999-11e8-858e-f32aab81782b.png">
OR
<img width="159" alt="screen shot 2018-08-06 at 4 52 11 pm" src="https://user-images.githubusercontent.com/18640514/43720632-53fd4b1e-9999-11e8-9461-24fe9dfe7efd.png">

**Comment by bluelovers** [comment]
hmm this bug only happen on webstorm

idea didn't has this error

still trying look what worng lol

**Comment by bluelovers** [comment]
@skalashnyk try this

[releases.zip](https://github.com/bluelovers/idea-run-typescript/files/2268979/releases.zip)

**Comment by bluelovers** [comment]
@skalashnyk can u try download this file then install it , see does it work for u or not?

**Comment by skalashnyk** [comment]
@bluelovers, now it works, thanks!
