### ISSUE TITLE
Node Debug Config doesn't use the same values

### ISSUE THREAD

**Issue by Garethp** [bluelovers/idea-run-typescript#12]
Two things run config settings I've noticed that don't translate over:

 * Working Directory
When I have nested directories (Using yarn workspaces for example), the run config for running Typescript will correctly pick up the closest `tsconfig.json` file to use as the working directory, but the node debug config will use the root directory. This results in the run and debug having different config files that might have differences in them

 * Environment Variables
When I set a default environment variable for a typescript file, it doesn't exist when I try to debug that file, even though it exists when I run it through typescript

**Comment by bluelovers** [comment]
new version uploaded

https://plugins.jetbrains.com/plugin/10841-run-configuration-for-typescript/versions/stable/94936

**Comment by Garethp** [comment]
I'll have a bigger merge request in a day or so. One that fixes the debug to work naturally instead of as a separate action
