### ISSUE TITLE
怎么只有Run按钮，没有Debug按钮呢？

### ISSUE THREAD

**Issue by xbdtb** [bluelovers/idea-run-typescript#2]
看代码里面好像有Debug相关的Action啊

**Comment by bluelovers** [comment]
@xbdtb 因為不知道 如何如何 符合 interface

所以雖然有預定想做出來 但作不出來

**Comment by xbdtb** [comment]
[![](https://raw.githubusercontent.com/xbdtb/idea-run-typescript/master/config.png)](https://raw.githubusercontent.com/xbdtb/idea-run-typescript/master/config.png)
@bluelovers 你好，像上面这样添加一个node.js模版的配置，在Javascript File中填写ts文件，然后在Node parameters中填写ts-node的注册参数--require ts-node/register，就是把普通的js文件改成ts文件，加一个node参数就能Debug并下断点调试了。但是Web Storm中默认是不识别ts文件，右键菜单也没有Run和Debug的选项，只能手动去添加，比较麻烦。既然在现有模版下手工配置能实现，插件只要能识别ts文件，根据现有模版创建一个配置，并添加node参数就行了。但由于对Idea的插件机制不熟悉，只希望这些信息能帮助到您。

**Comment by bluelovers** [comment]
@xbdtb 不適用於插件機制xd

---

不過呢
這裡有另外一種實現方式

https://github.com/xiyuan-fengyu/IdeaPluginTypeScriptExecutor

他是利用現有的 js run conf 去做(雖然可以 run/debug
但實際上是把編譯好的 js 加入 run conf 內
只是把顯示名稱改成 .ts

**Comment by xbdtb** [comment]
@bluelovers 我看到了这个插件，不是想要的那种，靠自动或手动去编译生成js，在多项目多个tsconfig.json下会乱套，生成的js位置也不对，可能这个原因这个插件我安装了没有任何效果，看来还不如自己直接在生成目录比如dist下启动js文件进行调试了，生成map文件一样能在ts文件里进入断点，唯一的问题就是生成目录里杂乱文件太多，要随意找启动文件会比较累，不如在源码目录里简单清晰

**Comment by bluelovers** [comment]
@xbdtb 靠官方的插件api說明 的話 連這個插件都做不出來

所以也無法指望官方手冊能有任何線索 來實作 這部分= =

**Comment by bluelovers** [comment]
@xbdtb 剛忽然想起來 之前忘了說

我在做這個插件出來之前 都是用這個方法來跑 ts 缺點就是 要自己手動改檔名的部分就是

ts-node 的部份 則可以設為專案預設值

![2018-09-20-06-24-22-6](https://user-images.githubusercontent.com/167966/45785182-f587b880-bc9d-11e8-80cc-1ae42c3a6037.png)

**Comment by xbdtb** [comment]
@bluelovers 了解了，谢谢您！不过和我上面贴的图的方法原理差不多，都是利用ts-node，都是要手动添加配置

**Comment by bluelovers** [comment]
@xbdtb 新版已增加 DEBUG 按鈕

(採用 寫入原始 NodeJS Run Conf 模式，放棄做不出來的插件實現)
