### ISSUE TITLE
在vm里添加 -Dfile.encoding=UTF-8 解决了输出简中的错误, 但是还是有乱码的显示.

### ISSUE THREAD

**Issue by semanticDao** [bluelovers/idea-run-typescript#38]
![image](https://user-images.githubusercontent.com/102669067/162872749-bd188d29-1144-41a4-9f50-74264e6d50fe.png)

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-run-typescript/issues/32

不知道如何解決這個問題 在舊版本的 IDEA 系列內 不會出現這個 但自從最近幾個版本開始 就這樣了
