### ISSUE TITLE
中文乱码。

### ISSUE THREAD

**Issue by whtiehack** [bluelovers/idea-run-typescript#4]
感谢这个插件。的确有用。
但是有个乱码问题

![image](https://user-images.githubusercontent.com/12741016/55934545-7a024e80-5c63-11e9-92f1-a909ec88d490.png)

如果用这个命令行手动运行是没有问题的
![image](https://user-images.githubusercontent.com/12741016/55934577-92726900-5c63-11e9-900a-7471155b0226.png)

感谢。

**Comment by bluelovers** [comment]
hmm 我在繁體 windows 內是可以正常輸出 中文的

你試試看將 ts 檔存成 utf8

**Comment by whtiehack** [comment]
本来就是UTF8哦。 webstorm创建的文件默认都是utf8

哈哈。
```
hmm 鎴戝湪绻侀珨 windows 鍏ф槸鍙互姝ｅ父杓稿嚭 涓枃鐨�

浣犺│瑭︾湅灏� ts 妾斿瓨鎴� utf8
```

![image](https://user-images.githubusercontent.com/12741016/55965600-7f828780-5ca9-11e9-9a11-68d2bcf0f33d.png)

**Comment by bluelovers** [comment]
hmm 這我就不知道問題點在哪裡了 猜不出來

![image](https://user-images.githubusercontent.com/167966/55979775-8b7c4280-5cc5-11e9-9253-7c626df66c01.png)

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/56006418-4ed13b00-5d07-11e9-9203-648cbd5ae766.png)



![image](https://user-images.githubusercontent.com/12741016/56006423-5264c200-5d07-11e9-8450-9fab9c2353fb.png)


js是没有问题的。。有点纠结呀。

**Comment by bluelovers** [comment]
@whtiehack 在 vmoption 裡面加上這一段

```
-Dfile.encoding=UTF-8
```

**Comment by whtiehack** [comment]
@bluelovers  试了一下。没问题了。 感谢感谢。

**Comment by EsanL** [comment]
> @whtiehack在 vmoption 里面加上了这一段
> 
> ```
> -Dfile.encoding=UTF-8
> ```

请问vmoption 在哪里呢？安装目录里面的webstorm64.exe.vmoptions文件吗？

**Comment by EsanL** [comment]
> @whtiehack 在 vmoption 裡面加上這一段
> 
> ```
> -Dfile.encoding=UTF-8
> ```

搞定了，多谢！

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/139523426-c9642149-7b26-4dec-8ba2-f5240b201b2f.png)

![image](https://user-images.githubusercontent.com/167966/139523490-973987e8-77b6-4b72-a53e-82786651ebc4.png)
