### ISSUE TITLE
报错找不到module ts-node/register

### ISSUE THREAD

**Issue by ligenxun** [bluelovers/idea-run-typescript#41]
"D:\Program Files\nodejs\node.exe" --require ts-node/register D:/MyCode/python/test_ts_s.ts
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module 'ts-node/register'
Require stack:
- internal/preload
?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:833:27)?[39m
?[90m    at Module.require (node:internal/modules/cjs/loader:1057:19)?[39m
?[90m    at Module._preloadModules (node:internal/modules/cjs/loader:1332:12)?[39m
?[90m    at loadPreloadModules (node:internal/bootstrap/pre_execution:583:5)?[39m
?[90m    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:95:3)?[39m
?[90m    at node:internal/main/run_main_module:9:1?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'internal/preload'?[39m ]
}

进程已结束，退出代码为 1

node.js的版本是：
node --version
v16.18.0

这个是因为最新版本不支持导致的么？

**Comment by bluelovers** [comment]
你要自己額外安裝 ts-node

**Comment by ligenxun** [comment]
好的，OK了，感谢感谢
