### ISSUE TITLE
Passing ts-node parameters

### ISSUE THREAD

**Issue by Baptiste-Garcin** [bluelovers/idea-run-typescript#43]
Hi,

Is there a way to pass argument to ts-node while creating a run configuration ?

The plugin is passing a `--loader` parameter to node and therefore, I can't pass a `--files` to `ts-node`…

Am I missing something ?

Thanks

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/212166643-d48520f3-55c9-472e-82d1-14fff70bad10.png)
