### ISSUE TITLE
Option to specify default TypeScript Node package

### ISSUE THREAD

**Issue by jadenv** [bluelovers/idea-run-typescript#45]
`tsx`, `esno`. `ts-node`, and `esm-ts-node` are all supported TypeScript Node packages.

However, there is no way to specify a default if your project has multiple installed that can be discovered.

Editing the Run/Debug Configuration Templates and setting a different TypeScript Node packages does not seem to have any effect.

It is tedious when right clicking a file and creating a new config to have to immediately edit it to run with the different package.

**Comment by Lordfirespeed** [comment]
I'm working on this issue, but I'm afraid I've made extensive changes to the project (fully rewritten), so not sure if my changes will be merge-friendly

**Comment by dangnhdev** [comment]
Is there any way I can do this while waiting for the new project to be released? For example modify plugin code and reinstall it manually?

**Comment by Lordfirespeed** [comment]
I released my own version of the plugin, but it isn't in a great state: https://plugins.jetbrains.com/plugin/22824-run-configuration-for-typescript

**Comment by awattez** [comment]
Thank you for your work on this plugin! I wanted to inquire if there's any plan to add support for using the tsx package (https://github.com/privatenumber/tsx) as an alternative to ts-node. This package provides a very convenient way to run TypeScript in Node.js, and having an easy option to select it in the plugin would be highly beneficial.

Is this feature on the roadmap or planned for future updates?

Thanks in advance for your response!

**Comment by jadenv** [comment]
Native support was added to directly run and debug TypeScript files, so this will no longer be necessary 😊

https://www.jetbrains.com/phpstorm/whatsnew/#frontend

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-run-typescript/issues/48
