### ISSUE TITLE
Add ability to run TS scratch files

### ISSUE THREAD

**Issue by pelepelin** [bluelovers/idea-run-typescript#5]
There are "run" and "save" options in the drop-down menu of a normal file tab, however, they are not present for "scratch file" tab.

**Comment by bluelovers** [comment]
where is "scratch file", can u give screenshot , let me see how to go and view it

**Comment by NorthFury** [comment]
You can create one by using `File -> New -> Scratch File`.

**Comment by bluelovers** [comment]
@NorthFury @pelepelin support at v2020.2.19.0

**Comment by bluelovers** [comment]
```
// @ts-ignore
console.log(process.cwd())
```

`process.cwd()` will be project root

![image](https://user-images.githubusercontent.com/167966/74806194-4468d000-5320-11ea-8964-7f76875cd7de.png)
